print "Starting maya loading and fbx conversion \n";
	
if (`file -q -exists "/Users/Mina/Desktop/Fall 2016/BuildingWorlds/MidTerm1/MidTerm1/Assets/Objects/Metronum.mb"`)
{		
	file -o "/Users/Mina/Desktop/Fall 2016/BuildingWorlds/MidTerm1/MidTerm1/Assets/Objects/Metronum.mb";
	FBXExportEmbeddedTextures -v false;
	// FBXExportHardEdges -v true;
	FBXExportApplyConstantKeyReducer -v false;
	FBXExportShowUI -v false;

	print "Before fbx export\n";
	FBXExport -f "/Users/Mina/Desktop/Fall 2016/BuildingWorlds/MidTerm1/MidTerm1/Temp/ExportedFBXFile.fbx";
	print "after fbx export\n";
}
else
	print "Could not open Maya file.";


system ("rm \"/Users/Mina/Desktop/Fall 2016/BuildingWorlds/MidTerm1/MidTerm1/Temp/CommandPipe\"");

$donepipeKill = `fopen "/Users/Mina/Desktop/Fall 2016/BuildingWorlds/MidTerm1/MidTerm1/Temp/SyncPipeKill" "w"`;
fwrite $donepipeKill "Done";
fclose $donepipeKill;
